config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :pastsales
  resources :upcomingsales
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'upcomingsales#index'

  get '/calc', to: 'calculator#calcview'
  get '/ckgclerk', to: 'calculator#ckgclerk'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/pastsale.rb
class Pastsale < ApplicationRecord
end

app/controllers/pastsales_controller.rb
class PastsalesController < ApplicationController
  before_action :set_pastsale, only: %i[ show edit update destroy ]

  # GET /pastsales or /pastsales.json
  def index
    @pastsales = Pastsale.all
  end

  # GET /pastsales/1 or /pastsales/1.json
  def show
  end

  # GET /pastsales/new
  def new
    @pastsale = Pastsale.new
  end

  # GET /pastsales/1/edit
  def edit
  end

  # POST /pastsales or /pastsales.json
  def create
    @pastsale = Pastsale.new(pastsale_params)

    respond_to do |format|
      if @pastsale.save
        format.html { redirect_to pastsale_url(@pastsale), notice: "Pastsale was successfully created." }
        format.json { render :show, status: :created, location: @pastsale }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pastsale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pastsales/1 or /pastsales/1.json
  def update
    respond_to do |format|
      if @pastsale.update(pastsale_params)
        format.html { redirect_to pastsale_url(@pastsale), notice: "Pastsale was successfully updated." }
        format.json { render :show, status: :ok, location: @pastsale }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pastsale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pastsales/1 or /pastsales/1.json
  def destroy
    @pastsale.destroy

    respond_to do |format|
      format.html { redirect_to pastsales_url, notice: "Pastsale was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pastsale
      @pastsale = Pastsale.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pastsale_params
      params.require(:pastsale).permit(:salename, :location, :site, :sale_id, :date)
    end
end

app/helpers/pastsales_helper.rb
module PastsalesHelper
end

app/views/pastsales/_form.html.erb
<%= form_with(model: pastsale) do |form| %>
  <% if pastsale.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(pastsale.errors.count, "error") %> prohibited this pastsale from being saved:</h2>

      <ul>
        <% pastsale.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :salename, style: "display: block" %>
    <%= form.text_field :salename %>
  </div>

  <div>
    <%= form.label :location, style: "display: block" %>
    <%= form.text_field :location %>
  </div>

  <div>
    <%= form.label :site, style: "display: block" %>
    <%= form.text_field :site %>
  </div>

  <div>
    <%= form.label :sale_id, style: "display: block" %>
    <%= form.number_field :sale_id %>
  </div>

  <div>
    <%= form.label :date, style: "display: block" %>
    <%= form.date_field :date %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/pastsales/_pastsale.html.erb
<div id="<%= dom_id pastsale %>">
  <p>
    <strong>Salename:</strong>
    <%= pastsale.salename %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= pastsale.location %>
  </p>

  <p>
    <strong>Site:</strong>
    <%= pastsale.site %>
  </p>

  <p>
    <strong>Sale:</strong>
    <%= pastsale.sale_id %>
  </p>

  <p>
    <strong>Date:</strong>
    <%= pastsale.date %>
  </p>

</div>

app/views/pastsales/edit.html.erb
<h1>Editing pastsale</h1>

<%= render "form", pastsale: @pastsale %>

<br>

<div>
  <%= link_to "Show this pastsale", @pastsale %> |
  <%= link_to "Back to pastsales", pastsales_path %>
</div>

app/views/pastsales/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Past sales</h1>

<table id="pastsales">
<tr><td><h6>Date</h6></td><td><h6>Sale</h6></td><td><h6>Location</h6></td><td><h6>Site</h6></td><td><h6>Sale ID</h6></td><td><h6>Starting At</h6></td></tr>
  <% @pastsales.each do |pastsale| %>
    <tr>
    <td><%= pastsale.date %></td>
    <td><%= pastsale.salename %></td>
    <td><%= pastsale.location %></td>
    <td><%= pastsale.site %></td>
    <td><%= pastsale.sale_id %></td>
    <td><%= link_to "Results", pastsale, class: "btn" %></td>
    <td><%= link_to "Replay", pastsale, class: "btn" %></td>
        <td><a class='dropdown-trigger btn' href='#' data-target='dropdown1'>▼Actions</a>
        <!-- Dropdown Structure -->
        <ul id='dropdown1' class='dropdown-content'>
          <li><a href="#!">one</a></li>
          <li><a href="#!">two</a></li>
          <li class="divider" tabindex="-1"></li>
          <li><a href="#!">three</a></li>
          <li><a href="#!"><i class="material-icons">view_module</i>four</a></li>
          <li><a href="#!"><i class="material-icons">cloud</i>five</a></li>
        </ul>
        </td>
    </tr>
  <% end %>
</table>

app/views/pastsales/new.html.erb
<h1>New pastsale</h1>

<%= render "form", pastsale: @pastsale %>

<br>

<div>
  <%= link_to "Back to pastsales", pastsales_path %>
</div>

app/views/pastsales/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @pastsale %>

<div>
  <%= link_to "Edit this pastsale", edit_pastsale_path(@pastsale) %> |
  <%= link_to "Back to pastsales", pastsales_path %>

  <%= button_to "Destroy this pastsale", @pastsale, method: :delete %>
</div>