config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :pastsales
  resources :upcomingsales
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'upcomingsales#index'

  get '/calc', to: 'calculator#calcview'
  get '/ckgclerk', to: 'calculator#ckgclerk'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/upcomingsale.rb
class Upcomingsale < ApplicationRecord
end

app/controllers/upcomingsales_controller.rb
class UpcomingsalesController < ApplicationController
  before_action :set_upcomingsale, only: %i[ show edit update destroy ]

  # GET /upcomingsales or /upcomingsales.json
  def index
    @upcomingsales = Upcomingsale.all
  end

  # GET /upcomingsales/1 or /upcomingsales/1.json
  def show
  end

  # GET /upcomingsales/new
  def new
    @upcomingsale = Upcomingsale.new
  end

  # GET /upcomingsales/1/edit
  def edit
  end

  # POST /upcomingsales or /upcomingsales.json
  def create
    @upcomingsale = Upcomingsale.new(upcomingsale_params)

    respond_to do |format|
      if @upcomingsale.save
        format.html { redirect_to upcomingsale_url(@upcomingsale), notice: "Sale was successfully created." }
        format.json { render :show, status: :created, location: @upcomingsale }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @upcomingsale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /upcomingsales/1 or /upcomingsales/1.json
  def update
    respond_to do |format|
      if @upcomingsale.update(upcomingsale_params)
        format.html { redirect_to upcomingsale_url(@upcomingsale), notice: "Sale was successfully updated." }
        format.json { render :show, status: :ok, location: @upcomingsale }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @upcomingsale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /upcomingsales/1 or /upcomingsales/1.json
  def destroy
    @upcomingsale.destroy

    respond_to do |format|
      format.html { redirect_to upcomingsales_url, notice: "Sale was successfully deleted." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_upcomingsale
      @upcomingsale = Upcomingsale.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def upcomingsale_params
      params.require(:upcomingsale).permit(:salename, :location, :site)
    end
end

app/helpers/upcomingsales_helper.rb
module UpcomingsalesHelper
end

app/views/upcomingsales/_form.html.erb
<%= form_with(model: upcomingsale) do |form| %>
  <% if upcomingsale.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(upcomingsale.errors.count, "error") %> prohibited this sale from being saved:</h2>

      <ul>
        <% upcomingsale.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :salename, style: "display: block" %>
    <%= form.text_field :salename %>
  </div>

  <div>
    <%= form.label :location, style: "display: block" %>
    <%= form.text_field :location %>
  </div>

  <div>
    <%= form.label :site, style: "display: block" %>
    <%= form.text_field :site %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/upcomingsales/_upcomingsale.html.erb
<div id="<%= dom_id upcomingsale %>">
  <p>
    <strong>Salename:</strong>
    <%= upcomingsale.salename %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= upcomingsale.location %>
  </p>

  <p>
    <strong>Site:</strong>
    <%= upcomingsale.site %>
  </p>

</div>

app/views/upcomingsales/edit.html.erb
<h1>Editing upcomingsale</h1>

<%= render "form", upcomingsale: @upcomingsale %>

<br>

<div>
  <%= link_to "Show this sale", @upcomingsale %> |
  <%= link_to "Back to upcoming sales", upcomingsales_path %>
</div>

app/views/upcomingsales/index.html.erb
<p style="color: green"><%= notice %></p>




<div class= 'col s10 m10 offset-s1 offset-m1'>
<div class="card">
<div class="card-content" style="text-align: center;">
<h3>Upcoming sales</h3>
    <ul>
    <div><h4>Filter By</h4></div>
    <li><td id="no-width"><button class="btn-large" onclick="getsales('')"><h6 id="top filter">All Sales</h6></button></td><td id="no-width"><button class="btn-large"><h6 id="top filter">Commercial</h6></td><td id="no-width"><button class="btn-large"><h6 id="top filter">Seed Stock</h6></button></td></li>
    <li class="collapsible-body"><td id="no-width" style="text-align: center;"><button class="btn-large"><h6>All Sales</h6></button></td><td id="no-width"><button class="btn-large"><h6>Commercial</h6></td><td id="no-width"><button class="btn-large"><h6>Seed Stock</h6></button></td></li>
    <li class="collapsible-body"><td id="no-width" style="text-align: center;"><button class="btn-large"><h6>All Sales</h6></button></td><td id="no-width"><button class="btn-large"><h6>Commercial</h6></td><td id="no-width"><button class="btn-large"><h6>Seed Stock</h6></button></td></li>
    </ul>
    <%= link_to "Create New sale", new_upcomingsale_path, class: "btn" %>
</div>
</div>
</div>

  <ul class="pagination">
    <li class="disabled"><a href="#!"><i class="material-icons">chevron_left</i></a></li>
    <li class="active"><a href="#!">1</a></li>
    <li class="waves-effect"><a href="#!">2</a></li>
    <li class="waves-effect"><a href="#!">3</a></li>
    <li class="waves-effect"><a href="#!">4</a></li>
    <li class="waves-effect"><a href="#!">5</a></li>
    <li class="waves-effect"><a href="#!"><i class="material-icons">chevron_right</i></a></li>
  </ul>
    <table>
      <tr><td><h6>Date</h6></td><td><h6>Sale</h6></td><td><h6>Location</h6></td><td><h6>Site</h6></td><td><h6>Sale ID</h6></td><td><h6>Starting At</h6></td></tr>
      <% @upcomingsales.each do |upcomingsale| %>
        <tr>
        <td><%= upcomingsale.date %></td>
        <td><%= upcomingsale.salename %></td>
        <td><%= upcomingsale.location %></td>
        <td><%= upcomingsale.site %></td>
        <td><%= upcomingsale.sale_id %></td>
        <td><%= upcomingsale.starting %></td>
        <td><%= link_to "View Sale Details", upcomingsale, class: "btn" %></td>
        <% if upcomingsale.sale_link.present?%>
        <td><%= link_to "Catalog", upcomingsale.sale_link, class: "btn" %></td>
        <% else %>
        <% end %>
        </tr>
      <% end %>
    </table>
  <ul class="pagination">
    <li class="disabled"><a href="#!"><i class="material-icons">chevron_left</i></a></li>
    <li class="active"><a href="#!">1</a></li>
    <li class="waves-effect"><a href="#!">2</a></li>
    <li class="waves-effect"><a href="#!">3</a></li>
    <li class="waves-effect"><a href="#!">4</a></li>
    <li class="waves-effect"><a href="#!">5</a></li>
    <li class="waves-effect"><a href="#!"><i class="material-icons">chevron_right</i></a></li>
  </ul>
    <%= link_to "Create New sale", new_upcomingsale_path, class: "btn" %>

app/views/upcomingsales/new.html.erb
<h1>New upcomingsale</h1>

<%= render "form", upcomingsale: @upcomingsale %>

<br>

<div>
  <%= link_to "Back to upcoming sales", upcomingsales_path %>
</div>

app/views/upcomingsales/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @upcomingsale %>

<div>
  <%= link_to "Edit this upcoming sale", edit_upcomingsale_path(@upcomingsale) %> |
  <%= link_to "Back to upcoming sales", upcomingsales_path %>

  <%= button_to "Delete this sale", @upcomingsale, method: :delete %>
</div>