config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :pastsales
  resources :upcomingsales
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'upcomingsales#index'

  get '/calc', to: 'calculator#calcview'
  get '/ckgclerk', to: 'calculator#ckgclerk'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/layouts/_footer.html.erb
        <footer class="page-footer">
          <div class="container">
            <div class="row">
              <div class="col l6 s12">
                <h5 class="white-text">The Stocklive Group</h5>
                <p class="grey-text text-lighten-4">When you can't get to the auction, StockLive takes you there. For support call us on 1300 259 742.</p>
              </div>
              <div class="col l4 offset-l2 s12">
                <h5 class="white-text">Follow Us</h5>
                <ul>
                  <li><a class="grey-text text-lighten-3" <%= link_to "Staff Sign In", new_user_session_path%></a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="footer-copyright">
            <div class="container">
            © 2022 Copyright OhMyGordon
            <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
            </div>
          </div>
        </footer>

app/views/layouts/_header.html.erb
  <nav>
    <div class="nav-'wrapper">
      <ul id="nav-mobile" class="left hide-on-med-and-down">
        <li style= "background-color: #ffffff;"><a class="brand-logo-left" href="/"><img style="max-width: 150px; max-height: 48px;"<%= image_tag "SLG.png"%></a></li>
        <li><%= link_to " $/HD Clerk", calc_path %></li>
        <li><%= link_to " C/KG Clerk", ckgclerk_path %></li>
        <li><%= link_to "Past Sales", pastsales_path %></li>
        <li><a href="badges.html">Contact Us</a></li>
        <li><a href="collapsible.html">About Us</a></li>
        <li><a href="collapsible.html">Support</a></li>
        <li><a href="collapsible.html">Media</a></li>
        <!-- % link_to image_tag('SLG.png'), root_path , id:"nav-mobile", class:"left hide-on-med-and-down"% -->
      </ul>
    </div>
  </nav>

  <%javascript_include_tag 'materialize' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
      <!--Import Google Icon Font-->
      <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
      <!--Import materialize.css-->
      <%= stylesheet_link_tag "materialize" %>
      

      <!--Let browser know website is optimized for mobile-->
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>
      <%= favicon_link_tag asset_path('icon.jpg') %>
      <%= javascript_importmap_tags %>
  </head>

  <body style="width: 100%; display: grid;" >
    <p class="notice" hidden><%= notice %></p>
    <p class="alert" hidden><%= alert %></p>
    <%= render 'layouts/header' %>
    <%= yield %>
          <%= javascript_include_tag "materialize"%>
          <!--JavaScript at end of body for optimized loading
      <script type="text/javascript" src="assets/materialize.min.js"></script> -->
  </body>
  <footer>
  <%= render "layouts/footer" %>
  </footer>
</html>